/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export { }

/* prettier-ignore */
declare module 'vue' {
	export interface GlobalComponents {
		Advancedset: typeof import('./components/advancedset.vue')['default']
		ElButton: typeof import('element-plus/es')['ElButton']
		ElCol: typeof import('element-plus/es')['ElCol']
		ElIcon: typeof import('element-plus/es')['ElIcon']
		ElInput: typeof import('element-plus/es')['ElInput']
		ElRow: typeof import('element-plus/es')['ElRow']
		ElSwitch: typeof import('element-plus/es')['ElSwitch']
		Modeset: typeof import('./components/modeset.vue')['default']
		Wifiset: typeof import('./components/wifiset.vue')['default']
	}
}
